### PR TITLE
New App: Instant App Details + all app's json data

### PR DESCRIPTION
**Pull request by N-Shar-ma**
@sahil-shubham

### CODE REVIEW

**Review by sahil-shubham — COMMENTED** [review]
Looks good, can you also include the script through which you generated the json in the first place?

**Comment by N-Shar-ma** [comment]
> Looks good, can you also include the script through which you generated the json in the first place?

I actually generated it through this instant app itself! That's what the copy button is for

**Comment by sahil-shubham** [comment]
Missed the query to data function 😅 Guess we won't need the json then. Rather than having a select we can try having a horizontal carousel, what do you think?

**Comment by N-Shar-ma** [comment]
> Rather than having a select we can try having a horizontal carousel, what do you think?

Yes, that was just temporary to get the app running asap.
> Guess we won't need the json then. 

I actually meant to use it for the docs website marketplace to read from for now. That's why the copy button is commented as temporary, it was used to get the json and isn't needed now

**Comment by sahil-shubham** [comment]
Understood, thanks for taking the time to explain everything.

**Pull request merged**
