### PR TITLE
Source of code snippet

### PR DESCRIPTION
**Pull request by rajivharlalka**
The UI also shows the source of code as we currently have two origins of code-snippets
- The Algorithms repository
- Rosetta code
image

### CODE REVIEW

**Comment by rajivharlalka** [comment]
Search Query to test out both sources
Rosetta code
```
word wrap in c
word wrap in javascript
```

The Algorithms
```
bubble sort in c
merge sort in javascript
```

**Review by sahil-shubham — APPROVED** [review]

**Comment by hargup** [comment]
Screenshot 2021-12-15 at 10 31 24 PM


@rajivharlalka the app doesn't show up on felvin.com, is it deployed?

**Comment by rajivharlalka** [comment]
I dont think the app has been deployed, it can tested from the sandbox website

**Comment by sahil-shubham** [comment]
It should be visible now.

**Pull request merged**
