### PR TITLE
Add "Contribute" footer link

### PR DESCRIPTION
**Pull request by boehs**

### CODE REVIEW

**Review by sahil-shubham — COMMENTED** [review]
Thanks for showing interest in this project @boehs I appreciate your making this pull request but we already have a better indicator for this being open source on the top right of the screen. 
image

The "contribute" link doesn't seem that easy to find in the footer compared to the above. What do you think?

**Comment by hargup** [comment]
@sahil-shubham the aim of @boehs 's contribution is probably to indicate the contribution link in the main website, felvin.com doesn't link to this repo.

Anyway showing the contribution link in footer in the sandbox doesn't hurt as well. Hence I am merging this. @sahil-shubham lets make this change in felvin.com as well.

@boehs thanks for the contribution.

Screenshot 2021-10-02 at 12 58 54 AM

**Comment by boehs** [comment]
Well, this was merged but looking at the main site I can not find the github icon you speak of on the site 😕 , I wonder why this is.

**Comment by sahil-shubham** [comment]
@boehs Good question. This repository stands as a development environment for making "instant apps", these instant apps are packaged and published to npm. From where we pull this into our code for felvin.com, we have decided not to make that public. 

So only the changes to apps are carried forward to the main website, everything else stays to this repository.

**Comment by boehs** [comment]
> @boehs Good question. This repository stands as a development environment for making "instant apps", these instant apps are packaged and published to npm. From where we pull this into our code for felvin.com, we have decided not to make that public.
> 
> So only the changes to apps are carried forward to the main website, everything else stays to this repository. I have made the changes done by you into the other repository and you would be able to see them in a few minutes.

No, I understand that bit, but I can't find the actual icon you mention here:

> Thanks for showing interest in this project @boehs I appreciate you making this pull request but we already have a better indicator for this being open source on the top right of the screen.

**Comment by hargup** [comment]
Hi @boehs,
Sorry for the confusion, we have two websites, [sandbox.felvin.com](sandbox.felvin.com) and  [felvin.com](felvin.com). We were using [sandbox.felvin.com](sandbox.felvin.com) for deployment preview of instant apps, it had the github icon.

Main website, felvin.com, doesn't have the github icon because it is targeted at general audience, not just developers. The contribution link on the footer is useful, thanks for pointing it out and making the contribution.

**Comment by boehs** [comment]
> Hi @boehs, Sorry for the confusion, we have two websites, [sandbox.felvin.com](sandbox.felvin.com) and [felvin.com](felvin.com). We were using [sandbox.felvin.com](sandbox.felvin.com) for deployment preview of instant apps, it had the github icon.
> 
> Main website, felvin.com, doesn't have the github icon because it is targeted at general audience, not just developers. The contribution link on the footer is useful, thanks for pointing it out and making the contribution.

Got it, thank you!

**Pull request merged**
