### PR TITLE
Attempt to fix XSS vulnerability by removing possibly dangerous dependencies

### LINKED ISSUE #319: Possible vulnerability to XSS attack in JSON to CSV due to dependency
## Affected search queries

json to csv

## Summary

The instant app has a dependency `react-json-pretty` which uses `dangerouslySetInnerHtml` in its source code. Since we're dealing with user entered data here which is parsed, manipulated and rendered using this dependency, it may be vulnerable to XSS attacks.

## Possible solution

Remove the dependency and find an alternate way to render the generated CSV (maybe using the HTML `pre` tag?)

## Your Environment

- Browser information (Edge):
- Operating system: (Windows 10)

### PR DESCRIPTION
**Pull request by N-Shar-ma**
Should fix #319 

using pre tag instead of jsonPretty to pretty print csv. Tested manually

### CODE REVIEW

**Comment by hargup** [comment]
LGTM, thanks!

**Comment by sahil-shubham** [comment]
@N-Shar-ma is there any reason to why we didn't remove the package `react-json-pretty` from the following apps: 
- [ ] csv-to-json
- [ ] json-formatter
- [ ] yaml-to-json

Could you remove or find another package to replace this with? Let me know if you want me to it.

**Comment by N-Shar-ma** [comment]
@sahil-shubham The reason is elaborated [here](https://github.com/felvin-search/Instant-Apps-Browser-Extension/issues/3). But as you rightly noticed, this package has been used in other older instant apps so it is not the source of the bug. So removing it from these other apps will have the benefit of reducing a dependency, but that is it and it is not high priority at the moment

**Comment by sahil-shubham** [comment]
@N-Shar-ma good work on solving the error, if possible can you mention the explanation in #319 and close it? I don't think someone else in the future would be able to figure out things if needed considering it's a private repository. Even I am not supposed to be able to access that link 😅 (cc: @hargup)

**Pull request merged**
