### PR TITLE
Refactor project to create separate package for each app

### PR DESCRIPTION
**Pull request by OrkoHunter**
This PR makes a sweeping change to the repository. It
* Creates separate packages for each app. Inside `app/*`. Each app will be published at `@felvin-search-apps/<app-id>`
* Creates a thin @felvin-search/apps` package which re-exports all instant apps. (To be used by felvin.com)
* Creates a core package `@felvin-search/core` with utility functions, types, Standard UI components.
* Replaces create-react-app with webpack-dev-server based sandbox.
* Upgrades yarn to yarn v2 for better workspaces support (`yarn workspace foreach` is a nice command to run a command in all workspaces at once).

Co-authored-by: Sahil Shubham <sahil.shubham2000@gmail.com>

### CODE REVIEW

**Comment by sahil-shubham** [comment]
I am adding the two new apps in this branch.

**Comment by sahil-shubham** [comment]
Trying to fix the merge conflicts.

**Comment by sahil-shubham** [comment]
So this easily tops as the lengthiest rebase I ever did. We would have to look into optimizing some things because the build files are humongous.

**Comment by OrkoHunter** [comment]
@sahil-shubham :shipit:

**Comment by hargup** [comment]
@sahil-shubham we are also committing a lot of yarn cache files in this PR. We should probably ignore them.

**Comment by OrkoHunter** [comment]
@hargup Yeah, we checked and it looks like yarn v2 recommends committing cache files in the project https://github.com/yarnpkg/berry/tree/master/.yarn/cache

Definitely needs investigation. 💯

**Comment by hargup** [comment]
Cool, cool. Let's ship it 🤘

**Comment by OrkoHunter** [comment]
🟢

**Comment by OrkoHunter** [comment]
Press the button Sahil

**Pull request merged**
