### PR TITLE
fix publishing of cheat-sh app

### PR DESCRIPTION
**Pull request by hargup**

### CODE REVIEW

**Comment by hargup** [comment]
cc @sahil-shubham @N-Shar-ma Apprently the trouble was with the names starting with `cheat`, replaced it with `cht` and it works now. It might be an interesting exercise to try figure out why that was the case.

**Comment by sahil-shubham** [comment]
Npm does have some reserved keywords jut couldn't confirm if "cheat" was one lf them.

**Comment by hargup** [comment]
@sahil-shubham can you try to resolve the yarn errors?

**Comment by hargup** [comment]
Awesome! This did the job 🎉
Please merge if you think the PR is ready.

**Comment by sahil-shubham** [comment]
Thanks for fixing this @hargup changing the name of the package was the best way I could think as well

**Pull request merged**
