### PR TITLE
An Instant app to create notes

### PR DESCRIPTION
**Pull request by chirag-ghosh**
screenshot

### CODE REVIEW

**Comment by chirag-ghosh** [comment]
Note: I was unable to install package with my version of yarn `3.0.2`. Hence, I downgraded it to version `1.22.18`
I guess that is the reason for large changes in yarn.lock file

**Comment by hargup** [comment]
@chirag-ghosh @rajivharlalka Can you create a small gif/loom of the app to show it in action?

**Comment by rajivharlalka** [comment]
Sure, would make one.

**Comment by hargup** [comment]
Closing this for lack of activity

**Pull request closed without merging**
